output_root: '../'
pytorch_data_dir: '/datadrive/pytorch-data/'
experiment_name: "exp1"
log_dir: "unsup_cal"
azureml_logging: True
submitting_to_aml: False

# Loader params
num_workers: 24

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
