output_root: '../'
pytorch_data_dir: '/datadrive/pytorch-data/'
experiment_name: "eval1"
res: 224
#res: 320
batch_size: 128
num_workers: 12
n_classes: 27

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
